name: CI

on: 'pull_request'

jobs:
    ci:
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.0'
            -   run: composer install
            -   run: make test

